baseURL = "https://nadavrec.ca"
languageCode = "en-us"
title = "Nadav Recca"


theme                   = "quincy"

[params]
    footerText          = "n a d a v r e c c a ."
    HomeLinkText        = "Home."

[[params.mainMenu]]
    link = "/about"
    text = "animal"

[[params.mainMenu]]
    link = "/projects"
    text = "vegetable"

[[params.mainMenu]]
    link = "/gallery"
    text = "mineral"



